### PR TITLE
[Feature] Next Highest Quality

### PR DESCRIPTION
**Pull request by sblmnl**
Adds option to select the next highest playback quality if the preferred quality is not available.

### CODE REVIEW

**Comment by james-fray** [comment]
@sblmnl thanks!

**Comment by james-fray** [comment]
since i wasn't sure why you re-set an already selected quality, I removed the `setPlaybackQuality` from:

https://github.com/james-fray/YouTube-HD/blob/master/v3/data/main.js#L88
https://github.com/james-fray/YouTube-HD/blob/master/v3/data/main.js#L93

**Comment by sblmnl** [comment]
@james-fray happy to contribute!

i added that extra call to `setPlaybackQuality()` to force the player to use the currently selected quality instead of `auto` (which can change at any time).

the `player.getPlaybackQuality()` doesn't tell you if it's using `auto` playback quality.

**Comment by james-fray** [comment]
I see. Since the observer watches quality changes and makes adjustments if the criteria are not met, we can skip it. Additionally, note that having the automatic option allows the player to switch to higher qualities without interruption.

**Pull request merged**
